name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: test-pipeline
      run: echo $GITHUB_REF_NAME

  build-image-and-push-to-registry:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: andresrv94/golearn_rest_api:latest